const SIGN_UP = "SIGN_UP";
const CREATE_PRODUCT = "CREATE_PRODUCT";
const EDIT_PRODUCT = "EDIT_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const SEARCH_PRODUCT = "SEARCH_PRODUCT";
const FILTER_SPORT = "FILTER_SPORT";
const FILTER_GENRE = "FILTER_GENRE";
const FILTER_NAV_GENDER = "FILTER_NAV_GENDER";
const FILTER_BRAND = "FILTER_BRAND";
const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PAGINATED_PRODUCTS = "GET_PAGINATED_PRODUCTS";
const CHECK_LOGIN = "CHECK_LOGIN";
const LOGOUT = "LOGOUT";
const ORDER_BY = "ORDER_BY";
const ORDER_BY_PRICE = "ORDER_BY_PRICE";
const DETAIL_PRODUCT = "DETAIL_PRODUCT";
const ADD_TO_CART = "ADD_TO_CART";
const DELETE_FROM_CART = "DELETE_FROM_CART";
const DELETE_ALL_FROM_CART = "DELETE_ALL_FROM_CART";
const UPDATE_ITEM_NUM = "UPDATE_ITEM_NUM";
const REMOVE_DUPLICATES_CART = "REMOVE_DUPLICATES_CART";
const CREATE_USER = "CREATE_USER";
const FETCH_SAVED_ITEMS = "FETCH_SAVED_ITEMS";
const ADD_TO_CART_DETAIL = "ADD_TO_CART_DETAIL";
const FILTER_BRAND_CAROUSEL = "FILTER_BRAND_CAROUSEL";
const REMEMBER_PASSWORD = "REMEMBER_PASSWORD";
const RESET_PASSWORD = "RESET_PASSWORD";

module.exports = {
  SIGN_UP,
  CREATE_PRODUCT,
  EDIT_PRODUCT,
  DELETE_PRODUCT,
  SEARCH_PRODUCT,
  FILTER_SPORT,
  FILTER_GENRE,
  FILTER_BRAND,
  GET_PRODUCTS,
  FILTER_NAV_GENDER,
  GET_PAGINATED_PRODUCTS,
  CHECK_LOGIN,
  LOGOUT,
  ORDER_BY,
  ORDER_BY_PRICE,
  DETAIL_PRODUCT,
  ADD_TO_CART,
  DELETE_FROM_CART,
  DELETE_ALL_FROM_CART,
  UPDATE_ITEM_NUM,
  REMOVE_DUPLICATES_CART,
  CREATE_USER,
  FETCH_SAVED_ITEMS,
  ADD_TO_CART_DETAIL,
  REMEMBER_PASSWORD,
  RESET_PASSWORD
};
