const SIGN_UP = "SIGN_UP";
const SEARCH_PRODUCT = "SEARCH_PRODUCT";
const FILTER_SPORT = "FILTER_SPORT";
const FILTER_GENRE = "FILTER_GENRE";
const FILTER_NAV_GENDER = "FILTER_NAV_GENDER";
const FILTER_BRAND = "FILTER_BRAND";
const GET_PRODUCTS = "GET_PRODUCTS";
const GET_PAGINATED_PRODUCTS = "GET_PAGINATED_PRODUCTS";

module.exports = {
  SIGN_UP,
  SEARCH_PRODUCT,
  FILTER_SPORT,
  FILTER_GENRE,
  FILTER_BRAND,
  GET_PRODUCTS,
  FILTER_NAV_GENDER,
  GET_PAGINATED_PRODUCTS
};
