const SIGN_UP = 'SIGN_UP';
const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
const FILTER_SPORT = 'FILTER_SPORT'
const FILTER_GENRE = 'FILTER_GENRE'
const FILTER_BRAND = 'FILTER_BRAND'
const GET_PRODUCTS = 'GET_PRODUCTS'
const DETAIL_PRODUCT = 'DETAIL_PRODUCT'


module.exports = {
    SIGN_UP,
    SEARCH_PRODUCT,
    FILTER_SPORT,
    FILTER_GENRE,
    FILTER_BRAND,
    GET_PRODUCTS,
    DETAIL_PRODUCT
}
